#!/bin/sh
#
# start/stop ddns-updater daemon.

### BEGIN INIT INFO
# Provides:          ddns-updater
# Required-Start:    $network $local_fs
# Required-Stop:     $network $local_fs
# Default-Start:     S 2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: DDNS Updater
# Description:       Update DDNS entry using current external IP address
### END INIT INFO

. /lib/lsb/init-functions

OPTIONS="-c /etc/ddns-updater/ddns.conf"
if [ -f /etc/default/ddns-updater ]; then
  . /etc/default/ddns-updater
fi

case "$1" in
    start)
	log_begin_msg "Starting ddns-updater..."
	pid=$( pidofproc -p /var/run/ddns-updater.pid /usr/local/bin/ddns-updater )
	if [ -n "$pid" ] ; then
	      log_begin_msg "Already running."
	      log_end_msg 0
	      exit 0
	fi
	start-stop-daemon --start --quiet --oknodo --exec /usr/local/bin/ddns-updater --background --make-pidfile --pidfile /var/run/ddns-updater.pid -- $OPTIONS
	log_end_msg $?

	;;
    stop)
	log_begin_msg "Stopping ddns-updater..."
	start-stop-daemon --stop --quiet --oknodo --exec /usr/bin/python --pidfile /var/run/ddns-updater.pid
	log_end_msg $?
	;;
    force-reload)
	$0 restart
	;;
    restart)
	$0 stop
	$0 start
	;;
    status)
	status_of_proc -p /var/run/ddns-updater.pid /usr/bin/python ddns-updater && exit 0 || exit $?
	;;
    *)
	log_success_msg "Usage: /etc/init.d/ddns-updater {start|stop|force-reload|restart|status}"
	exit 1
	;;
esac

exit 0
